# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:       
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          base_indepth: yes
          config_order: base.header, base.activity+community, base.repositories, languages, topics
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          commits_authoring: Guilherme Rosental, gkrosental, gkrosental@hotmail.com
          plugin_languages_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons 
